import numpy as onp


def get_bnorm(path_bnorm: str, plasma) -> np.ndarray:
    """
    Compute the target magnetic field from a file generated by STELLOPT code BNORM.
    The target is the normal inward magnetic field on the plasma surface.
    This magnetic field is normalized by curpol : the real target magnetic field is curpol * bnorm.
    The curpol number is found in the nescin file generated by BNORM.

    Args:
        path_bnorm (str): Path to bnorm file
        plasma (PlasmaSurface): The plasma surface

    Returns:
        np.ndarray: Normal B field on the plasma surface
    """
    # Read the data from the bnorm file
    data = []
    with open(path_bnorm, "r") as f:
        for line in f:
            data.append(str.split(line))
    adata = onp.array(data, dtype="float64")
    m, n, bmn = adata[:, 0], adata[:, 1], adata[:, 2]

    # Compute the normalized magnetic field
    bnorm = onp.zeros((plasma.grids[0]).shape)
    for i in range(len(m)):
        # Calculate the sum of the normalized magnetic field components
        bnorm += bmn[i] * onp.sin(
            2 * np.pi * m[i] * plasma.grids[0] +
            2 * np.pi * n[i] * plasma.grids[1]
        )

    return bnorm
